######################################################################
# Automatically generated by qmake (3.0) Thu Oct 13 23:20:27 2016
######################################################################

TEMPLATE = app
TARGET = throttleitem_example
INCLUDEPATH += .

# Input
HEADERS += controller.h \
    throttleitem.h
SOURCES += controller.cpp main.cpp \
    throttleitem.cpp
QT += quick
RESOURCES += resources.qrc
